### PR TITLE
Register anchors in ServerRedoc component

### LINKED ISSUE #321: Redocusaurus should collect heading ids / anchors
Hi

With Docusaurus v3.1 we introduced a broken anchors checker:

https://docusaurus.io/blog/releases/3.1#broken-anchors-checker

https://docusaurus.io/docs/docusaurus-core#useBrokenLinks

This requires collecting anchors for headings you create, otherwise Docusaurus doesn't know about those created anchors.

CleanShot 2024-01-08 at 15 43 17@2x

Note this api exists in Docusaurus 3.1 but not in 3.0 so you probably want to release a new major version requiring Docusaurus 3.1 to support this.

--- 

See also a Docusaurus user that gets reported Redocusaurus anchors links as broken:

https://github.com/facebook/docusaurus/issues/6810#issuecomment-1879387076

### PR DESCRIPTION
**Pull request by ctreatma**
This uses the `useBrokenLinks` Docusaurus hook to register Redoc-generated anchors so that Redocusaurus users can configure their sites to fail to build if there are broken anchors.

The ServerRedoc component is the only one that registers anchors because if a Redoc page is rendered on the client side it is too late to register anchors for the Docusaurus build.

Closes #321

### CODE REVIEW

File: packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx [hunk 1]
```diff
@@ -45,4 +48,23 @@ function ServerRedoc(
   );
 }
 
+function collectMenuItemAnchors(menuItems: IMenuItem[], parentAnchor = "") {
+  menuItems.forEach((menuItem) => {
+    // Register anchor for menu item
+    useBrokenLinks().collectAnchor(menuItem.id);
```
Comment (rohit-gohri) [inline packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx:54]: doesn't this break rules of hooks?

File: packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx [hunk 2]
```diff
@@ -25,6 +26,8 @@ function ServerRedoc(
     optionsOverrides,
   );
 
+  collectMenuItemAnchors(store.menu.items);
```
Comment (rohit-gohri) [inline packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx:29]:
```suggestion
  const {collectAnchor} = useBrokenLinks();
  collectMenuItemAnchors(store.menu.items, collectAnchor);
```

File: packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx (hunk 1 above)
Comment (ctreatma) [reply packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx]: Thanks!  Was not aware of the guidance around calling hooks, just stopped once I got something working.  I've updated to memoize the broken link checker, along the lines of the suggestion in your other comment.

**Review by rohit-gohri — APPROVED** [review]

File: packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx [hunk 3]
```diff
@@ -25,6 +26,9 @@ function ServerRedoc(
     optionsOverrides,
   );
 
+  const collector = useBrokenLinks();
+  collectMenuItemAnchors(collector, store.menu.items);
```
[the remark this answers is not in the document]
Comment (rohit-gohri) [reply packages/docusaurus-theme-redoc/src/theme/Redoc/ServerRedoc.tsx:30]: the number of hydration warnings are same before/after this PR. can fix them separately

**Comment by rohit-gohri** [comment]
thanks! 🎉

**Comment by rohit-gohri** [comment]
Released in https://github.com/rohit-gohri/redocusaurus/releases/tag/v2.3.0
